"use client";
import {
  Activity,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Battery,
  Calendar,
  ChevronRight,
  Clock,
  Command,
  File,
  FileText,
  Folder,
  HelpCircle,
  Home,
  Image,
  Info,
  Link,
  Maximize2,
  Menu,
  MessageCircle,
  Minimize2,
  Moon,
  Music,
  Power,
  RefreshCw,
  Save,
  Settings,
  Shield,
  Sun,
  Trash2,
  User,
  Video,
  Volume2,
  Wifi,
  X,
} from 'lucide-react';

export const Icons = {
  activity: Activity,
  alertCircle: AlertCircle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  battery: Battery,
  calendar: Calendar,
  chevronRight: ChevronRight,
  clock: Clock,
  close: X,
  command: Command,
  file: File,
  fileText: FileText,
  folder: Folder,
  helpCircle: HelpCircle,
  home: Home,
  image: Image,
  info: Info,
  link: Link,
  maximize: Maximize2,
  menu: Menu,
  messageCircle: MessageCircle,
  minimize: Minimize2,
  moon: Moon,
  music: Music,
  power: Power,
  refresh: RefreshCw,
  save: Save,
  settings: Settings,
  shield: Shield,
  sun: Sun,
  trash: Trash2,
  user: User,
  video: Video,
  volume2: Volume2,
  wifi: Wifi,
} as const; 